In [1]:
import pandas as pd

In [14]:
df1998_2010 = pd.read_csv('data(concat)/1998_2010.csv', index_col = 0).reset_index().drop(columns='index')
df2011_2016 = pd.read_csv('data(concat)/2011_2016.csv', index_col = 0).reset_index().drop(columns='index')
df2017_2022 = pd.read_csv('data(concat)/2017_2022.csv', index_col = 0).reset_index().drop(columns='index')

In [15]:
df1998_2010

           언론사           날짜                                     제목
0         연합뉴스  1998.05.20.                             주가 사흘째 상승세
1         연합뉴스  1998.05.20.                아남텔레콤, PDA 데이터 전송서비스 개시
2         연합뉴스  1998.05.20.                <회전목마> 삼성전자, 사이버 사외보 제작
3         연합뉴스  1998.05.20.               <주식시황> 사흘째 상승, 3백70선 다가서
4         연합뉴스  1998.05.20.                  -춘계승마- 신창무,싼졸쥬마장마술 우승
...        ...          ...                                    ...
667057  파이낸셜뉴스      A18면 2단        [CES2011]세계 최대 가전쇼 열리는 라스베이거스는?
667058    매일경제       9면 TOP         갤럭시 플레이어 미리 만나볼까, 본격출시전 체험단 모집
667059     뉴스핌        9면 3단                  <스페셜인터뷰> 천정훈 MIT 석좌교수
667060  헤럴드POP       12면 3단                     갤럭시S 닮은꼴 'N스크린' 공개
667061   미디어오늘       4면 TOP  “2011년 1000만원이 1억 될 종목” 묻지마 쩜상이 기대된다!

[667062 rows x 3 columns]

In [16]:
df2017_2022

,언론사,날짜,제목
0,아주경제,2017.01.01.,"특검,문형표 구속에 새해 첫날 안종범 재소환..삼성 합병에 박근혜 역할 집중..."
1,중앙SUNDAY,2017.01.01.,1308조원
2,IT조선,2017.01.01.,[2017 스마트폰 트렌드] ①스마트폰 시장 ‘흐림’ 전망...탈출구 있나
3,전자신문,33면 1단,"[신년기획]인공지능, 올해 경쟁력 확보 원년"
4,EBN,2017.01.01.,[주간증시전망] CES發 IT섹터 관심 다양화·삼성전자 실적 발표 등 대장주 상...
...,...,...,...
1713557,한국경제,2022.07.21.,"디지털이미지뱅크, 한투등 3개사서 20억원 투자 유치"
1713558,한국경제,2022.07.21.,[코스닥공시] 세보기계
1713559,한국경제,2022.07.21.,전자.통신업체 신용등급도 급상승세
1713560,한국경제,2022.07.21.,"종합주가 폭락세, 916.01(-37.21) 전장마감"
1713561,한국경제,2022.07.21.,"산자부, 수치제어장치 산.학.연 공동연구 개발에 성공"

In [18]:
df = pd.concat([df1998_2010, df2017_2022])
df

          언론사           날짜                             제목
0        연합뉴스  1998.05.20.                     주가 사흘째 상승세
1        연합뉴스  1998.05.20.        아남텔레콤, PDA 데이터 전송서비스 개시
2        연합뉴스  1998.05.20.        <회전목마> 삼성전자, 사이버 사외보 제작
3        연합뉴스  1998.05.20.       <주식시황> 사흘째 상승, 3백70선 다가서
4        연합뉴스  1998.05.20.          -춘계승마- 신창무,싼졸쥬마장마술 우승
...       ...          ...                            ...
1713557  한국경제  2022.07.21.  디지털이미지뱅크, 한투등 3개사서 20억원 투자 유치
1713558  한국경제  2022.07.21.                   [코스닥공시] 세보기계
1713559  한국경제  2022.07.21.             전자.통신업체 신용등급도 급상승세
1713560  한국경제  2022.07.21.  종합주가 폭락세, 916.01(-37.21) 전장마감
1713561  한국경제  2022.07.21.  산자부, 수치제어장치 산.학.연 공동연구 개발에 성공

[2380624 rows x 3 columns]

In [19]:
df.drop_duplicates()

          언론사           날짜                             제목
0        연합뉴스  1998.05.20.                     주가 사흘째 상승세
1        연합뉴스  1998.05.20.        아남텔레콤, PDA 데이터 전송서비스 개시
2        연합뉴스  1998.05.20.        <회전목마> 삼성전자, 사이버 사외보 제작
3        연합뉴스  1998.05.20.       <주식시황> 사흘째 상승, 3백70선 다가서
4        연합뉴스  1998.05.20.          -춘계승마- 신창무,싼졸쥬마장마술 우승
...       ...          ...                            ...
1713557  한국경제  2022.07.21.  디지털이미지뱅크, 한투등 3개사서 20억원 투자 유치
1713558  한국경제  2022.07.21.                   [코스닥공시] 세보기계
1713559  한국경제  2022.07.21.             전자.통신업체 신용등급도 급상승세
1713560  한국경제  2022.07.21.  종합주가 폭락세, 916.01(-37.21) 전장마감
1713561  한국경제  2022.07.21.  산자부, 수치제어장치 산.학.연 공동연구 개발에 성공

[2331956 rows x 3 columns]