In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train = pd.read_csv('train_imputed.csv')
train.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V304,V306,V307,V308,V310,V312,V313,V314,V315,V317
0,2987000.0,0.0,86400.0,68.500000,4.0,13926.0,441.0,150.0,1.0,142.0,...,0.0,0.000000,117.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,117.0
1,2987001.0,0.0,86401.0,29.000000,4.0,2755.0,404.0,150.0,2.0,102.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
2,2987002.0,0.0,86469.0,59.000000,4.0,4663.0,490.0,150.0,4.0,166.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
3,2987003.0,0.0,86499.0,50.000000,4.0,18132.0,567.0,150.0,2.0,117.0,...,0.0,50.000000,1758.000000,925.000000,354.0000,135.0,0.0000,0.0000,0.0000,1404.0
4,2987004.0,0.0,86506.0,50.000000,1.0,4497.0,514.0,150.0,2.0,102.0,...,1.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,3577535.0,0.0,15811047.0,49.000000,4.0,6550.0,523.8,150.0,4.0,226.0,...,0.0,0.000000,47.950001,0.000000,47.9375,0.0,47.9375,47.9375,47.9375,0.0
590536,3577536.0,0.0,15811049.0,39.500000,4.0,10444.0,225.0,150.0,2.0,224.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
590537,3577537.0,0.0,15811079.0,30.953125,4.0,12037.0,595.0,150.0,2.0,224.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
590538,3577538.0,0.0,15811088.0,117.000000,4.0,7826.0,481.0,150.0,2.0,224.0,...,0.0,117.000000,2903.500000,117.000000,669.5000,117.0,317.5000,669.5000,317.5000,2234.0
590539,3577539.0,0.0,15811131.0,280.000000,4.0,15066.0,170.0,150.0,2.0,102.0,...,0.0,279.950012,279.950012,279.950012,0.0000,0.0,0.0000,0.0000,0.0000,0.0

In [4]:
train

,Unnamed: 0.1,Unnamed: 0,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,...,V304,V306,V307,V308,V310,V312,V313,V314,V315,V317
0,0,0.0,2987000.0,0.0,86400.0,68.500000,4.0,13926.0,441.0,150.0,...,0.0,0.000000,117.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,117.0
1,1,1.0,2987001.0,0.0,86401.0,29.000000,4.0,2755.0,404.0,150.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
2,2,2.0,2987002.0,0.0,86469.0,59.000000,4.0,4663.0,490.0,150.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
3,3,3.0,2987003.0,0.0,86499.0,50.000000,4.0,18132.0,567.0,150.0,...,0.0,50.000000,1758.000000,925.000000,354.0000,135.0,0.0000,0.0000,0.0000,1404.0
4,4,4.0,2987004.0,0.0,86506.0,50.000000,1.0,4497.0,514.0,150.0,...,1.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,590535,590535.0,3577535.0,0.0,15811047.0,49.000000,4.0,6550.0,523.8,150.0,...,0.0,0.000000,47.950001,0.000000,47.9375,0.0,47.9375,47.9375,47.9375,0.0
590536,590536,590536.0,3577536.0,0.0,15811049.0,39.500000,4.0,10444.0,225.0,150.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
590537,590537,590537.0,3577537.0,0.0,15811079.0,30.953125,4.0,12037.0,595.0,150.0,...,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.0000,0.0000,0.0
590538,590538,590538.0,3577538.0,0.0,15811088.0,117.000000,4.0,7826.0,481.0,150.0,...,0.0,117.000000,2903.500000,117.000000,669.5000,117.0,317.5000,669.5000,317.5000,2234.0
590539,590539,590539.0,3577539.0,0.0,15811131.0,280.000000,4.0,15066.0,170.0,150.0,...,0.0,279.950012,279.950012,279.950012,0.0000,0.0,0.0000,0.0000,0.0000,0.0

In [ ]:
# setosa는 세모, versicolor는 네모, virginica는 동그라미로 표현
markers=['^', 's', 'o']

# setosa의 target 값은 0, versicolor는 1, virginica는 2. 각 target별로 다른 모양으로 산점도로 표시
for i, marker in enumerate(markers):
    x_axis_data = irisDF[irisDF['target'] == i]['sepal_length']
    y_axis_data = irisDF[irisDF['target'] == i]['sepal_width']
    plt.scatter(x_axis_data, y_axis_data, marker=marker, label=iris.target_names[i])
    
plt.legend()
plt.xlabel('sepal length') # x축
plt.ylabel('sepal width') # y축
plt.show()

In [ ]:
# 사이킷런의 StandardScaler를 이용해 평균이 0, 분산이 1인 표준 정규 분포로 근사
from sklearn.preprocessing import StandardScaler

# Target 값을 제외한 모든 속성 값을 StandardScaler를 이용해 표준 정규 분포를 가지는 값들로 변환
iris_scaled = StandardScaler().fit_transform(irisDF.drop('target', axis=1))
iris_scaled[:3]

In [ ]:
# 사이킷런은 PCA 변환을 위해 PCA 클래스를 제공
from sklearn.decomposition import PCA

# PCA 클래스는 n_components라는 PCA로 변환할 차원의 수를 의미하는 생성 파라미터를 인자로 받음
pca = PCA(n_components=2)

#fit()과 transform()을 호출해 PCA 변환 데이터 반환
pca.fit(iris_scaled)
iris_pca = pca.transform(iris_scaled)
print(iris_pca.shape)

In [ ]:
# numpy결과값을 pandas dataframe으로 변경
# PCA 변환된 데이터의 칼럼 명을 각각 pca_component_1, pca_component_2로 명명
pca_columns = ['pca_component_1', 'pca_component_2']
irisDF_pca = pd.DataFrame(iris_pca, columns = pca_columns)
irisDF_pca['target'] = iris.target
irisDF_pca.head(3)

In [ ]:
#setosa는 세모, versicolor는 네모, virginica는 동그라미로 표현
markers=['^', 's', 'o']

#setosa의 target 값은 0, versicolor는 1, virginica는 2. 각 target별로 다른 모양으로 산점도로 표시
for i, marker in enumerate(markers):
    x_axis_data = irisDF_pca[irisDF['target'] == i]['pca_component_1']
    y_axis_data = irisDF_pca[irisDF['target'] == i]['pca_component_2']
    plt.scatter(x_axis_data, y_axis_data, marker=marker, label=iris.target_names[i])
    
plt.legend()
plt.xlabel('pca_component_1')
plt.ylabel('pca_component_2')
plt.show()

In [ ]:
# explained_variance_ratio_ 속성은 전체 변동성에서 개별 PCA 컴포넌트별로 차이하는 변동성의 비율을 제공
print(pca.explained_variance_ratio_)