In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import urllib.request
from konlpy.tag import Okt
from tqdm import tqdm
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import sklearn

## 데이터 로드 및 train test로 분할

In [19]:
df = pd.read_csv('38_Oasis.csv').drop(columns = ['Unnamed: 0']).reset_index().drop(columns=['index','link','target'])

In [20]:
df.head()

,title,date,content
0,[제목 : [오아시스]\n 팬데믹시대에 내마음의 표준을 바꾸는 유통 ],2020-09-04,이번 코로나가 유통시장의 판도를 5년이상 앞당겨진 변화를 가져 왔다?매장에서 인테넷...
1,[제목 : [오아시스] 오아시스 매수 했습니다. ],2021-04-17,"오아이스 주식 중 pe가 보유한 물량이 시장에서 움직이는 듯 하네요.어제, 아시는..."
2,[제목 : [오아시스] 오아시스 매수 했습니다. ],2021-04-17,얼마에 사셨어요? 저도 관심이 있는데요.
3,[제목 : [오아시스]\n 오아시스 주식이요 ],2021-04-17,오아시스 주식을 사고싶어게시판에 올려봅니다파실분 계시면**** 팔육일팔 삼육사일로연...
4,[제목 : [오아시스] 70만원이면 비싼건가요 ],2021-04-19,"30주 70만원에 살려고하는데, 비싼건가요"

## null 값 확인

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    136 non-null    object
 1   date     136 non-null    object
 2   content  133 non-null    object
dtypes: object(3)
memory usage: 3.3+ KB

In [22]:
# NULL 값 있는 행 확인
df[df['content'].isnull()]

                                     title        date content
31              [제목 : [오아시스] 상장노력은 하는거죠? ]  2021-07-09     NaN
40                [제목 : [오아시스] 조용히 갑시다~~ ]  2021-07-16     NaN
43  [제목 : [오아시스] 지금 잘가고 있긴 한데 스피드 좀 올려~~ ]  2021-07-29     NaN

In [23]:
# 공백으로 NULL 값 채우기
df = df.fillna('')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    136 non-null    object
 1   date     136 non-null    object
 2   content  136 non-null    object
dtypes: object(3)
memory usage: 3.3+ KB

내용에 빈 값이 있지만 title에서 추출할 것이 있지 않을까 해서 공백으로 채워줌

## index 날짜로 바꿔주기

In [25]:
# date를 오름차순 정렬
df.date = df.date.sort_index(ascending=True)
# index로 설정
df = df.set_index('date')
df

,title,content
date,,
2020-09-04,[제목 : [오아시스]\n 팬데믹시대에 내마음의 표준을 바꾸는 유통 ],이번 코로나가 유통시장의 판도를 5년이상 앞당겨진 변화를 가져 왔다?매장에서 인테넷...
2021-04-17,[제목 : [오아시스] 오아시스 매수 했습니다. ],"오아이스 주식 중 pe가 보유한 물량이 시장에서 움직이는 듯 하네요.어제, 아시는..."
2021-04-17,[제목 : [오아시스] 오아시스 매수 했습니다. ],얼마에 사셨어요? 저도 관심이 있는데요.
2021-04-17,[제목 : [오아시스]\n 오아시스 주식이요 ],오아시스 주식을 사고싶어게시판에 올려봅니다파실분 계시면**** 팔육일팔 삼육사일로연...
2021-04-19,[제목 : [오아시스] 70만원이면 비싼건가요 ],"30주 70만원에 살려고하는데, 비싼건가요"
...,...,...
2022-08-31,[제목 : [오아시스] 우크라이나와 러시아 ],덩치 큰 러시아가 누구다 다 이길거라고 했지만 결과는? 길고 짧은건 대봐야 안다고우...
2022-08-31,"[제목 : [오아시스] 오늘 날짜(2022.08.31) 더벨 기사, 오아시스 기업...",코스닥 상장을 추진 중인 신선식품 새벽배송 기업 오아시스가 기업가치 목표를 최대 2...
2022-09-02,[제목 : [오아시스] 이 시기에 오히려 주목해야 할 기업 ],연일 금리가 급등하고 있다. 매출만을 키우기 위해 무한확장을 거듭했던 스타트업과 유...
2022-09-05,[제목 : [오아시스] 계획된 적자 ],한때 VC와 스타트업들이 힘을 합쳐 매출액을 늘려 시장 주도권을 가져가기위한 전략으...
2022-09-08,[제목 : [오아시스] 위기에 재조명받는 ‘오아시스·미트박스’…흑자비결은? ],오아시스마켓은 올해 상반기 전년 대비 21% 증가한 2024억원 매출액과 171% ...

## 특수문자 제거 정규표현식

In [26]:
df['title'] = df['title'].str.replace(r"[^\uAC00-\uD7A30-9a-zA-Z\s]",'')
df['content'] = df['content'].str.replace(r"[^\uAC00-\uD7A30-9a-zA-Z\s]",'')

C:\Users\hslio\AppData\Local\Temp\ipykernel_27768\1046961940.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['title'] = df['title'].str.replace(r"[^\uAC00-\uD7A30-9a-zA-Z\s]",'')
C:\Users\hslio\AppData\Local\Temp\ipykernel_27768\1046961940.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['content'] = df['content'].str.replace(r"[^\uAC00-\uD7A30-9a-zA-Z\s]",'')

In [27]:
df

,title,content
date,,
2020-09-04,제목 오아시스\n 팬데믹시대에 내마음의 표준을 바꾸는 유통,이번 코로나가 유통시장의 판도를 5년이상 앞당겨진 변화를 가져 왔다매장에서 인테넷의...
2021-04-17,제목 오아시스 오아시스 매수 했습니다,오아이스 주식 중 pe가 보유한 물량이 시장에서 움직이는 듯 하네요어제 아시는 분...
2021-04-17,제목 오아시스 오아시스 매수 했습니다,얼마에 사셨어요 저도 관심이 있는데요
2021-04-17,제목 오아시스\n 오아시스 주식이요,오아시스 주식을 사고싶어게시판에 올려봅니다파실분 계시면 팔육일팔 삼육사일로연락주세요
2021-04-19,제목 오아시스 70만원이면 비싼건가요,30주 70만원에 살려고하는데 비싼건가요
...,...,...
2022-08-31,제목 오아시스 우크라이나와 러시아,덩치 큰 러시아가 누구다 다 이길거라고 했지만 결과는 길고 짧은건 대봐야 안다고우크...
2022-08-31,제목 오아시스 오늘 날짜20220831 더벨 기사 오아시스 기업가치 최대 2조 제시,코스닥 상장을 추진 중인 신선식품 새벽배송 기업 오아시스가 기업가치 목표를 최대 2...
2022-09-02,제목 오아시스 이 시기에 오히려 주목해야 할 기업,연일 금리가 급등하고 있다 매출만을 키우기 위해 무한확장을 거듭했던 스타트업과 유니...
2022-09-05,제목 오아시스 계획된 적자,한때 VC와 스타트업들이 힘을 합쳐 매출액을 늘려 시장 주도권을 가져가기위한 전략으...
2022-09-08,제목 오아시스 위기에 재조명받는 오아시스미트박스흑자비결은,오아시스마켓은 올해 상반기 전년 대비 21 증가한 2024억원 매출액과 171 증가...

## 토큰화

In [28]:
okt = Okt()

In [29]:
# 불용어 처리 

stopwords = ['의','가','이','은','들','는','좀','잘','걍','과','도','를','으로','자','에','와','한','하다','\n','\n ', '제목']

In [30]:
token = []
for sentence in tqdm(df['title']):
    tokenized_sentence = okt.morphs(sentence, stem=True) # 토큰화
    stopwords_removed_sentence = [word for word in tokenized_sentence if not word in stopwords] # 불용어 제거
    token.append(stopwords_removed_sentence)

100%|███████████████████████████████████████████████████████████████████████████████| 136/136 [00:00<00:00, 609.87it/s]

In [46]:
len(token)

136

In [42]:
from collections import Counter

In [51]:
# 한 날짜? 한 행당 횟수 추출

for i in range(136):
    vocab = Counter(token[i])
    print(vocab)

Counter({'오아시스': 1, '팬데믹': 1, '시대': 1, '내': 1, '마음': 1, '표준': 1, '을': 1, '바꾸다': 1, '유통': 1})
Counter({'오아시스': 2, '매수': 1})
Counter({'오아시스': 2, '매수': 1})
Counter({'오아시스': 2, '주': 1, '식이': 1, '요': 1})
Counter({'오아시스': 1, '70만원': 1, '이면': 1, '비싸다': 1, '가요': 1})
Counter({'오아시스': 1, '70만원': 1, '이면': 1, '비싸다': 1, '가요': 1})
Counter({'코멘트': 1, '오아시스': 1, 'pe': 1, '가다': 1, '뭐': 1, '에요': 1})
Counter({'오아시스': 1, '망설이다': 1, '못': 1, '사다': 1})
Counter({'오아시스': 1, '위': 1, '글': 1, '바이럴': 1, '기': 1, '막히다': 1})
Counter({'오아시스': 2, '아직': 1, '모르다': 1, '때': 1, '빨리': 1, '사다': 1})
Counter({'비싸다': 2, '오아시스': 1, '너무': 1})
Counter({'코멘트': 1, '오아시스': 1, '그래도': 1, '지금': 1, '제일': 1, '싸다': 1, '겁니다': 1})
Counter({'비싸다': 2, '오아시스': 1, '너무': 1})
Counter({'오아시스': 2, '상장': 1, '언제': 1, '하나요': 1})
Counter({'오아시스': 1, '옆': 1, '집': 1, '수수': 1, '수지': 1, '그렇게': 1, '일': 1, '없다': 1})
Counter({'오아시스': 1, '거래': 1, '뜸': 1})
Counter({'코멘트': 1, '오아시스': 1, '그': 1, '놈': 1, '싸다': 1, '올리다': 1, '함': 1, '사보다': 1, '거래': 1})
Counter({'오아시스': 1, '옆': 1, '집': 1, '수수': 1, '수지': 1, '그렇게': 1, '일': 1, '없다': 1})
Counter({'오아시스': 1, '무상증자': 1, '알다': 1})
Counter({'오아시스': 1, '옆': 1, '집': 1, '수수': 1, '수지': 1, '그렇게': 1, '일': 1, '없다': 1})
Counter({'오아시스': 1, '1': 1, '백만원': 1, '거래': 1, '되다': 1})
Counter({'오아시스': 1, '매다': 1, '거래': 1, '되다': 1})
Counter({'오아시스': 1, '오늘': 1, '매수': 1})
Counter({'오아시스': 1, '중소기업': 1, '여부': 1})
Counter({'오아시스': 2, '코멘트': 1, '예상': 1, '말고': 1, '올해': 1, '실적': 1, '보다': 1, '2400억': 1, '정도인': 1})
Counter({'사다': 2, '코멘트': 1, '오아시스': 1, '71': 1, '크다': 1, '판돈': 1, '일부': 1, '자다': 1, '갈다': 1})
Counter({'년': 2, '오아시스': 1, '매출': 1, '3천억': 1, '안': 1, '되다': 1, '영': 1, '억': 1, '이익': 1, '100억': 1, '남짓': 1})
Counter({'오아시스': 1, '항상': 1, '지금': 1, '가장': 1, '저렴하다': 1, '임': 1})
Counter({'오아시스': 1, '유상증자': 1, '공시': 1, '네': 1, '요': 1})
Counter({'오아시스': 1, '유상증자': 1, '공시': 1, '네': 1, '요': 1})
Counter({'코멘트': 1, '오아시스': 1, '공시': 1, '나오다': 1})
Counter({'오아시스': 1, '상장': 1, '노력': 1})
Counter({'오아시스': 1, '무조건': 1, '상장': 1, '회': 1, '사다': 1})
Counter({'오아시스': 1, '이미': 1, '사다': 1})
Counter({'오아시스': 1, '물량많': 1, '네': 1})
Counter({'코멘트': 1, '오아시스': 1, '금액': 1})
Counter({'오아시스': 1, '실': 1, '거래': 1, '137만': 1})
Counter({'오아시스': 1, '가격': 1, '다르다': 1, '나': 1, '제대로': 1, '보다': 1})
Counter({'오아시스': 1, '가격': 1, '다르다': 1, '나': 1, '제대로': 1, '보다': 1})
Counter({'오아시스': 1, '성공하다': 1})
Counter({'오아시스': 1, '조용하다': 1, '가다': 1})
Counter({'오아시스': 1, '무상증자': 1, '액면': 1, '분할': 1, '언제나': 1})
Counter({'코멘트': 1, '오아시스': 1, '희망': 1, '을': 1, '먹다': 1, 'K': 1, '삼촌': 1})
Counter({'오아시스': 1, '지금': 1, '가다': 1, '있다': 1, '한데': 1, '스피드': 1, '올리다': 1})
Counter({'오아시스': 1, '일단': 1, '200': 1, '찍다': 1, '난후': 1, '무증': 1, '얘기': 1})
Counter({'오아시스': 1, '14677': 1, '주': 1, '1조': 1, '평가': 1, '로': 1, '나오다': 1})
Counter({'오아시스': 1, '쏘다': 1, '아시아': 1, '경제': 1, '이다': 1})
Counter({'코멘트': 1, '오아시스': 1, 'ib': 1, '에서': 1, '보다': 1, 'ipo': 1, '가치': 1, '1조': 1, '5천': 1, '입니다': 1, '상장': 1, '3조': 1})
Counter({'오아시스': 1, '팔': 1, '라고': 1, '계속': 1, '연락': 1, '오다': 1})
Counter({'오아시스': 1, '글로벌': 1, '4': 1, '대': 1, '사모': 1, '에서': 1, '1천억': 1, '들어온답니다': 1})
Counter({'코멘트': 1, '오아시스': 1, '우선주': 1, '로': 1, '투자': 1, '더': 1, '괜찮다': 1, '물량': 1, '부담': 1, '줄다': 1})
Counter({'오아시스': 1})
Counter({'오아시스': 2, '코멘트': 1, '앞': 1, '좋아지다': 1, '같다': 1})
Counter({'오아시스': 2, '상': 1, '장하다': 1, '최소': 1, '시': 1, '총': 1, '3조': 1})
Counter({'오아시스': 1, '반기': 1, '실적': 1, '나오다': 1})
Counter({'오아시스': 1, '오다': 1, '기': 1, '평': 1, '어떻다': 1})
Counter({'코멘트': 1, '오아시스': 1, '기': 1, '평': 1, '을': 1, '왜': 1})
Counter({'코멘트': 1, '오아시스': 1, '반기': 1, '실적': 1, '어디서': 1, '확인': 1, '하나요': 1, '전': 1, '자공시': 1, '없다': 1})
Counter({'오아시스': 1, '반기': 1, '실적': 1, '어디서': 1, '확인': 1, '하나요': 1})
Counter({'빠르다': 2, '오아시스': 1, '오다': 1, '쓱': 1})
Counter({'코멘트': 1, '오아시스': 1, '3000000': 1, '가다': 1})
Counter({'코멘트': 1, '오아시스': 1, '주다': 1, '4': 1, '백만원': 1, '넘기다': 1, '후': 1, '액': 1, '분과': 1, '무증': 1, '상장': 1, '신': 1})
Counter({'오아시스': 1, '주': 1, '식수': 1})
Counter({'오아시스': 1, '상장': 1, '청구': 1, '언제': 1, '신청': 1})
Counter({'코멘트': 1, '오아시스': 1, '고객': 1, '센터': 1, '악의': 1, '적': 1, '매물': 1, '신고': 1, '나다': 1, '신': 1})
Counter({'요': 2, '코멘트': 1, '오아시스': 1, '따위': 1, '답변': 1, '을': 1, '주네': 1, '이미': 1, '수': 1, '차례': 1, '안내': 1, '드리다': 1})
Counter({'오아시스': 1, '고객': 1, '센터': 1, '악의': 1, '적': 1, '매물': 1, '신고': 1, '요나': 1, '신': 1})
Counter({'오아시스': 1, '액': 1, '분': 1, '가다': 1})
Counter({'코멘트': 1, '오아시스': 1, '찬성': 1, '근데': 1, '현실': 1, '성은': 1, '액': 1, '분': 1, '5천원': 1, '에서': 1, '5': 1, '백원': 1, '후': 1})
Counter({'오아시스': 2, '기': 1, '평': 1, '청구': 1})
Counter({'오아시스': 1, '주식': 1, '수가': 1, '너무': 1, '적다': 1})
Counter({'오아시스': 2, '기': 1, '평': 1, '청구': 1})
Counter({'오아시스': 1, '주식': 1, '수가': 1, '너무': 1, '적다': 1})
Counter({'코멘트': 1, '오아시스': 1, '그렇다': 1, '오다': 1, '기': 1, '평': 1, '하': 1, '지': 1, '않다': 1, '상장': 1, '청구': 1, '바로': 1, '신청': 1})
Counter({'오아시스': 1, '그렇다': 1, '오다': 1, '기': 1, '평': 1, '하': 1, '지': 1, '않다': 1, '상장': 1, '청구': 1, '바로': 1, '신청': 1})
Counter({'오아시스': 1, '몇': 1, '일': 1, '만에': 1, '무슨': 1, '일이': 1, '죠': 1})
Counter({'오아시스': 1, '미치다': 1, '우상': 1, '향': 1})
Counter({'오아시스': 1, '매매': 1, '글': 1, '다': 1, '업자': 1, '밖에': 1, '없다': 1})
Counter({'오아시스': 1, '놈': 1, '만': 1, '걸리다': 1, '심보': 1})
Counter({'오아시스': 1, '왜케': 1, '떨어지다': 1, '가요': 1})
Counter({'오아시스': 1, '뭔': 1, '일': 1, '있다': 1, '건가': 1})
Counter({'오아시스': 2, '1조': 1, '기업': 1, '가치': 1})
Counter({'오아시스': 1, '100억원': 1, '규모': 1, '유상증자': 1})
Counter({'코멘트': 1, '오아시스': 1, '그': 1, '벨': 1, '류': 1, '비싸다': 1, '돈': 1, '안': 1, '모이다': 1})
Counter({'오아시스': 1, '차라리': 1, '아마존': 1, '을': 1, '사라': 1})
Counter({'오아시스': 1, '내년': 1, '3월': 1, '정기': 1, '주주총회': 1, '기대': 1, '되다': 1})
Counter({'오아시스': 1, '수익': 1, '보다': 1, '된거': 1, '지': 1, '뭐': 1})
Counter({'오아시스': 2, '22년': 1, '상장': 1, '축하': 1, '드리다': 1})
Counter({'오아시스': 1, '내년': 1, '상반기': 1, '실적': 1, '하반기': 1, '청구': 1})
Counter({'오아시스': 2, '예상': 1, '기업가': 1, '치다': 1, '1조': 1, '컬리': 1, '5조': 1})
Counter({'코멘트': 1, '오아시스': 1, '2조': 1, '이상': 1})
Counter({'오아시스': 1, '1조': 1, '누구': 1, '개': 1, '이름': 1, '인가': 1})
Counter({'코멘트': 1, '오아시스': 1, 'pre': 1, 'ipo': 1, '기관': 1, '투자': 1, '1조': 1, '밸류에': 1, '들어오다': 1, '아시': 1, '죠': 1, '안티': 1})
Counter({'오아시스': 1, '2조': 1, '부터': 1, '시작': 1})
Counter({'오아시스': 1, '2조': 1, '부터': 1, '시': 1, '작': 1, '공': 1, '모': 1, '가가': 1})
Counter({'오아시스': 1, '금년': 1, '상장': 1})
Counter({'오아시스': 1, '지금': 1, '가격': 1})
Counter({'오아시스': 1, '비상': 1, '장': 1, '주식': 1, '투자': 1, '권유': 1, '돈': 1, '달라': 1, '사람': 1, '극': 1, '주의': 1, '필요': 1, '사기꾼': 1})
Counter({'오아시스': 1, '가격': 1})
Counter({'코멘트': 1, '오아시스': 1, '하반기': 1, '되다': 1, '40': 1, '층': 1, '있다': 1, '겁니다': 1, '시간': 1, '두다': 1, '기다리다': 1, '보시': 1, '죠': 1})
Counter({'코멘트': 1, '오아시스': 1, '동감': 1, '1조': 1, '공모': 1, '상장': 1, '일': 1, '따블': 1, '2조': 1, '장외': 1, '2': 1, '지다': 1})
Counter({'오아시스': 1, 'SI': 1, '가다': 1, '1조': 1, '가치': 1, '들어오다': 1})
Counter({'오아시스': 1, '50분': 1, '1': 1, '로': 1, '액': 1, '분하다': 1, '주': 1, '총': 1, '내용': 1})
Counter({'오아시스': 1, '오다': 1, '액': 1, '분': 1, '50': 1, '배': 1, '라니': 1, '날아가다': 1})
Counter({'오아시스': 1, '오다': 1, '액': 1, '분': 1, '50': 1, '배': 1, '라니': 1, '날아가다': 1})
Counter({'오아시스': 1, '주': 1, '총': 1, '편지': 1, '써다': 1})
Counter({'오아시스': 1, '주': 1, '총': 1, '편지': 1, '써다': 1})
Counter({'오아시스': 1, '29일': 1, '까지': 1, '매수': 1, '되다': 1})
Counter({'주': 2, '오아시스': 1, '컬리': 1, '대': 1, '문제': 1})
Counter({'오아시스': 2, '액면': 1, '분할': 1, '날짜': 1})
Counter({'오아시스': 1, '4월': 1, '청구': 1, '예정': 1})
Counter({'코멘트': 1, '오아시스': 1, '액면': 1, '분할': 1, '하나요': 1})
Counter({'오아시스': 1, '주': 1, '총': 1, '참석': 1, '후기': 1})
Counter({'코멘트': 1, '오아시스': 1, '주': 1, '총': 1, '내용': 1, '감사하다': 1})
Counter({'코멘트': 1, '오아시스': 1, '주': 1, '총': 1, '내용': 1, '저': 1, '감사': 1, '드리다': 1, '3': 1, '백도': 1, '문제': 1, '없다': 1})
Counter({'오아시스': 1, '액면': 1, '분할': 1, '날짜': 1, '아시': 1, '분': 1})
Counter({'오아시스': 1, '주식': 1, '언제': 1})
Counter({'오아시스': 1, '혹시': 1, '지금': 1, '사면': 1, '호구': 1, '인가요': 1})
Counter({'오아시스': 2, '일': 2, '액면': 1, '분할': 1, '관련': 1, '기준': 1, '및': 1, '교부': 1})
Counter({'52일': 2, '코멘트': 1, '오아시스': 1, '까진': 1, '괜찮다': 1, '액': 1, '분': 1, '기준': 1, '일': 1, '임': 1})
Counter({'오아시스': 2, '일': 2, '액면': 1, '분할': 1, '관련': 1, '기준': 1, '및': 1, '교부': 1})
Counter({'오아시스': 1, '기업': 1, '가치': 1, '3': 1, '지다': 1, '언급': 1, '되다': 1})
Counter({'코멘트': 1, '오아시스': 1, '3': 1, '조': 1, '끄다': 1, '지다': 1, '라': 1, '쓰다': 1, '가려지다': 1, '욕': 1, '아니다': 1})
Counter({'오아시스': 1, '작년': 1, '에나': 1, '가능': 1})
Counter({'코멘트': 1, '오아시스': 1, '어디': 1, '에나': 1, '기': 1, '어나': 1, '오는': 1, '안티': 1})
Counter({'오아시스': 1, '기업': 1, '가치': 1, '3': 1, '지다': 1, '언급': 1, '되다': 1})
Counter({'오아시스': 2, '즈': 1, '아': 1})
Counter({'오아시스': 1, '액면': 1, '분할': 1, '완료': 1, '및': 1, '희망': 1, '회로': 1})
Counter({'코멘트': 1, '오아시스': 1, '성': 1, '장주': 1, '다': 1, '박살': 1, '나다': 1, '청구': 1, '못': 1})
Counter({'오아시스': 2, '쿠팡': 1, '상장': 1, '후': 1, '주식': 1, '반토막': 1, '컬리': 1, '적자': 1, '그나마': 1, '순': 1, '익': 1, '중': 1, '인데': 1, '업황': 1, '안좋다': 1})
Counter({'코멘트': 1, '오아시스': 1, '구르다': 1, '알다': 1, '있다': 1, '그냥': 1, '직접': 1, '올리다': 1})
Counter({'오아시스': 1, '우크라이나': 1, '러시아': 1})
Counter({'오아시스': 2, '오늘': 1, '날짜': 1, '20220831': 1, '더벨': 1, '기사': 1, '기업': 1, '가치': 1, '최대': 1, '2조': 1, '제시': 1})
Counter({'오아시스': 1, '시기': 1, '오히려': 1, '주목': 1, '기업': 1})
Counter({'오아시스': 1, '계획': 1, '되다': 1, '적자': 1})
Counter({'오아시스': 2, '위기': 1, '재': 1, '조명': 1, '받다': 1, '미트': 1, '박스': 1, '흑자': 1, '비결': 1})

In [53]:
# 전체 중 빈도수 출력

all_word_list = sum(token, [])
vocab = Counter(all_word_list)
print(vocab)

Counter({'오아시스': 156, '코멘트': 32, '상장': 12, '주': 11, '일': 11, '되다': 9, '기': 8, '1조': 8, '청구': 8, '비싸다': 7, '액면': 7, '분할': 7, '오다': 7, '총': 7, '액': 7, '가다': 6, '사다': 6, '없다': 6, '가치': 6, '평': 6, '분': 6, '을': 5, '요': 5, '지금': 5, '거래': 5, '실적': 5, '보다': 5, '주식': 5, '기업': 5, '2조': 5, '매수': 4, '너무': 4, '하나요': 4, '가격': 4, '있다': 4, '지다': 4, '3': 4, '가요': 3, '언제': 3, '옆': 3, '집': 3, '수수': 3, '수지': 3, '그렇게': 3, '올리다': 3, '유상증자': 3, '공시': 3, '네': 3, '나오다': 3, '로': 3, '에서': 3, '투자': 3, '반기': 3, '후': 3, '신': 3, '신청': 3, '드리다': 3, '지': 3, '죠': 3, '컬리': 3, '내용': 3, '날짜': 3, '기준': 3, '및': 3, '70만원': 2, '이면': 2, '뭐': 2, '못': 2, '글': 2, '싸다': 2, '겁니다': 2, '그': 2, '놈': 2, '무상증자': 2, '알다': 2, '1': 2, '백만원': 2, '오늘': 2, '예상': 2, '년': 2, '안': 2, '임': 2, '이미': 2, '다르다': 2, '나': 2, '제대로': 2, '희망': 2, '무증': 2, 'ipo': 2, '3조': 2, '4': 2, '대': 2, '괜찮다': 2, '시': 2, '어디서': 2, '확인': 2, '빠르다': 2, '고객': 2, '센터': 2, '악의': 2, '적': 2, '매물': 2, '신고': 2, '나다': 2, '수가': 2, '적다': 2, '그렇다': 2, '하': 2, '않다': 2, '바로': 2, '다': 2, '돈': 2, '내년': 2, '하반기': 2, '들어오다': 2, '아시': 2, '안티': 2, '부터': 2, '50': 2, '배': 2, '라니': 2, '날아가다': 2, '편지': 2, '써다': 2, '문제': 2, '관련': 2, '교부': 2, '52일': 2, '언급': 2, '에나': 2, '적자': 2, '팬데믹': 1, '시대': 1, '내': 1, '마음': 1, '표준': 1, '바꾸다': 1, '유통': 1, '식이': 1, 'pe': 1, '에요': 1, '망설이다': 1, '위': 1, '바이럴': 1, '막히다': 1, '아직': 1, '모르다': 1, '때': 1, '빨리': 1, '그래도': 1, '제일': 1, '뜸': 1, '함': 1, '사보다': 1, '매다': 1, '중소기업': 1, '여부': 1, '말고': 1, '올해': 1, '2400억': 1, '정도인': 1, '71': 1, '크다': 1, '판돈': 1, '일부': 1, '자다': 1, '갈다': 1, '매출': 1, '3천억': 1, '영': 1, '억': 1, '이익': 1, '100억': 1, '남짓': 1, '항상': 1, '가장': 1, '저렴하다': 1, '노력': 1, '무조건': 1, '회': 1, '물량많': 1, '금액': 1, '실': 1, '137만': 1, '성공하다': 1, '조용하다': 1, '언제나': 1, '먹다': 1, 'K': 1, '삼촌': 1, '한데': 1, '스피드': 1, '일단': 1, '200': 1, '찍다': 1, '난후': 1, '얘기': 1, '14677': 1, '평가': 1, '쏘다': 1, '아시아': 1, '경제': 1, '이다': 1, 'ib': 1, '5천': 1, '입니다': 1, '팔': 1, '라고': 1, '계속': 1, '연락': 1, '글로벌': 1, '사모': 1, '1천억': 1, '들어온답니다': 1, '우선주': 1, '더': 1, '물량': 1, '부담': 1, '줄다': 1, '앞': 1, '좋아지다': 1, '같다': 1, '상': 1, '장하다': 1, '최소': 1, '어떻다': 1, '왜': 1, '전': 1, '자공시': 1, '쓱': 1, '3000000': 1, '주다': 1, '넘기다': 1, '분과': 1, '식수': 1, '따위': 1, '답변': 1, '주네': 1, '수': 1, '차례': 1, '안내': 1, '요나': 1, '찬성': 1, '근데': 1, '현실': 1, '성은': 1, '5천원': 1, '5': 1, '백원': 1, '몇': 1, '만에': 1, '무슨': 1, '일이': 1, '미치다': 1, '우상': 1, '향': 1, '매매': 1, '업자': 1, '밖에': 1, '만': 1, '걸리다': 1, '심보': 1, '왜케': 1, '떨어지다': 1, '뭔': 1, '건가': 1, '100억원': 1, '규모': 1, '벨': 1, '류': 1, '모이다': 1, '차라리': 1, '아마존': 1, '사라': 1, '3월': 1, '정기': 1, '주주총회': 1, '기대': 1, '수익': 1, '된거': 1, '22년': 1, '축하': 1, '상반기': 1, '기업가': 1, '치다': 1, '5조': 1, '이상': 1, '누구': 1, '개': 1, '이름': 1, '인가': 1, 'pre': 1, '기관': 1, '밸류에': 1, '시작': 1, '작': 1, '공': 1, '모': 1, '가가': 1, '금년': 1, '비상': 1, '장': 1, '권유': 1, '달라': 1, '사람': 1, '극': 1, '주의': 1, '필요': 1, '사기꾼': 1, '40': 1, '층': 1, '시간': 1, '두다': 1, '기다리다': 1, '보시': 1, '동감': 1, '공모': 1, '따블': 1, '장외': 1, '2': 1, 'SI': 1, '50분': 1, '분하다': 1, '29일': 1, '까지': 1, '4월': 1, '예정': 1, '참석': 1, '후기': 1, '감사하다': 1, '저': 1, '감사': 1, '백도': 1, '혹시': 1, '사면': 1, '호구': 1, '인가요': 1, '까진': 1, '조': 1, '끄다': 1, '라': 1, '쓰다': 1, '가려지다': 1, '욕': 1, '아니다': 1, '작년': 1, '가능': 1, '어디': 1, '어나': 1, '오는': 1, '즈': 1, '아': 1, '완료': 1, '회로': 1, '성': 1, '장주': 1, '박살': 1, '쿠팡': 1, '반토막': 1, '그나마': 1, '순': 1, '익': 1, '중': 1, '인데': 1, '업황': 1, '안좋다': 1, '구르다': 1, '그냥': 1, '직접': 1, '우크라이나': 1, '러시아': 1, '20220831': 1, '더벨': 1, '기사': 1, '최대': 1, '제시': 1, '시기': 1, '오히려': 1, '주목': 1, '계획': 1, '위기': 1, '재': 1, '조명': 1, '받다': 1, '미트': 1, '박스': 1, '흑자': 1, '비결': 1})

In [54]:
word_list = list(vocab.keys())
word_list

['오아시스',
 '팬데믹',
 '시대',
 '내',
 '마음',
 '표준',
 '을',
 '바꾸다',
 '유통',
 '매수',
 '주',
 '식이',
 '요',
 '70만원',
 '이면',
 '비싸다',
 '가요',
 '코멘트',
 'pe',
 '가다',
 '뭐',
 '에요',
 '망설이다',
 '못',
 '사다',
 '위',
 '글',
 '바이럴',
 '기',
 '막히다',
 '아직',
 '모르다',
 '때',
 '빨리',
 '너무',
 '그래도',
 '지금',
 '제일',
 '싸다',
 '겁니다',
 '상장',
 '언제',
 '하나요',
 '옆',
 '집',
 '수수',
 '수지',
 '그렇게',
 '일',
 '없다',
 '거래',
 '뜸',
 '그',
 '놈',
 '올리다',
 '함',
 '사보다',
 '무상증자',
 '알다',
 '1',
 '백만원',
 '되다',
 '매다',
 '오늘',
 '중소기업',
 '여부',
 '예상',
 '말고',
 '올해',
 '실적',
 '보다',
 '2400억',
 '정도인',
 '71',
 '크다',
 '판돈',
 '일부',
 '자다',
 '갈다',
 '년',
 '매출',
 '3천억',
 '안',
 '영',
 '억',
 '이익',
 '100억',
 '남짓',
 '항상',
 '가장',
 '저렴하다',
 '임',
 '유상증자',
 '공시',
 '네',
 '나오다',
 '노력',
 '무조건',
 '회',
 '이미',
 '물량많',
 '금액',
 '실',
 '137만',
 '가격',
 '다르다',
 '나',
 '제대로',
 '성공하다',
 '조용하다',
 '액면',
 '분할',
 '언제나',
 '희망',
 '먹다',
 'K',
 '삼촌',
 '있다',
 '한데',
 '스피드',
 '일단',
 '200',
 '찍다',
 '난후',
 '무증',
 '얘기',
 '14677',
 '1조',
 '평가',
 '로',
 '쏘다',
 '아시아',
 '경제',
 '이다',
 'ib',
 '에서',
 'ipo',
 '가치',
 '5천',
 '입니다',
 '3조',
 '팔',
 '라고',
 '계속',
 '연락',
 '오다',
 '글로벌',
 '4',
 '대',
 '사모',
 '1천억',
 '들어온답니다',
 '우선주',
 '투자',
 '더',
 '괜찮다',
 '물량',
 '부담',
 '줄다',
 '앞',
 '좋아지다',
 '같다',
 '상',
 '장하다',
 '최소',
 '시',
 '총',
 '반기',
 '평',
 '어떻다',
 '왜',
 '어디서',
 '확인',
 '전',
 '자공시',
 '빠르다',
 '쓱',
 '3000000',
 '주다',
 '넘기다',
 '후',
 '액',
 '분과',
 '신',
 '식수',
 '청구',
 '신청',
 '고객',
 '센터',
 '악의',
 '적',
 '매물',
 '신고',
 '나다',
 '따위',
 '답변',
 '주네',
 '수',
 '차례',
 '안내',
 '드리다',
 '요나',
 '분',
 '찬성',
 '근데',
 '현실',
 '성은',
 '5천원',
 '5',
 '백원',
 '주식',
 '수가',
 '적다',
 '그렇다',
 '하',
 '지',
 '않다',
 '바로',
 '몇',
 '만에',
 '무슨',
 '일이',
 '죠',
 '미치다',
 '우상',
 '향',
 '매매',
 '다',
 '업자',
 '밖에',
 '만',
 '걸리다',
 '심보',
 '왜케',
 '떨어지다',
 '뭔',
 '건가',
 '기업',
 '100억원',
 '규모',
 '벨',
 '류',
 '돈',
 '모이다',
 '차라리',
 '아마존',
 '사라',
 '내년',
 '3월',
 '정기',
 '주주총회',
 '기대',
 '수익',
 '된거',
 '22년',
 '축하',
 '상반기',
 '하반기',
 '기업가',
 '치다',
 '컬리',
 '5조',
 '2조',
 '이상',
 '누구',
 '개',
 '이름',
 '인가',
 'pre',
 '기관',
 '밸류에',
 '들어오다',
 '아시',
 '안티',
 '부터',
 '시작',
 '작',
 '공',
 '모',
 '가가',
 '금년',
 '비상',
 '장',
 '권유',
 '달라',
 '사람',
 '극',
 '주의',
 '필요',
 '사기꾼',
 '40',
 '층',
 '시간',
 '두다',
 '기다리다',
 '보시',
 '동감',
 '공모',
 '따블',
 '장외',
 '2',
 '지다',
 'SI',
 '50분',
 '분하다',
 '내용',
 '50',
 '배',
 '라니',
 '날아가다',
 '편지',
 '써다',
 '29일',
 '까지',
 '문제',
 '날짜',
 '4월',
 '예정',
 '참석',
 '후기',
 '감사하다',
 '저',
 '감사',
 '3',
 '백도',
 '혹시',
 '사면',
 '호구',
 '인가요',
 '관련',
 '기준',
 '및',
 '교부',
 '52일',
 '까진',
 '언급',
 '조',
 '끄다',
 '라',
 '쓰다',
 '가려지다',
 '욕',
 '아니다',
 '작년',
 '에나',
 '가능',
 '어디',
 '어나',
 '오는',
 '즈',
 '아',
 '완료',
 '회로',
 '성',
 '장주',
 '박살',
 '쿠팡',
 '반토막',
 '적자',
 '그나마',
 '순',
 '익',
 '중',
 '인데',
 '업황',
 '안좋다',
 '구르다',
 '그냥',
 '직접',
 '우크라이나',
 '러시아',
 '20220831',
 '더벨',
 '기사',
 '최대',
 '제시',
 '시기',
 '오히려',
 '주목',
 '계획',
 '위기',
 '재',
 '조명',
 '받다',
 '미트',
 '박스',
 '흑자',
 '비결']

In [55]:
word_rank = list(vocab.values())
word_rank

[156,
 1,
 1,
 1,
 1,
 1,
 5,
 1,
 1,
 4,
 11,
 1,
 5,
 2,
 2,
 7,
 3,
 32,
 1,
 6,
 2,
 1,
 1,
 2,
 6,
 1,
 2,
 1,
 8,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 5,
 1,
 2,
 2,
 12,
 3,
 4,
 3,
 3,
 3,
 3,
 3,
 11,
 6,
 5,
 1,
 2,
 2,
 3,
 1,
 1,
 2,
 2,
 2,
 2,
 9,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 5,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 4,
 2,
 2,
 2,
 1,
 1,
 7,
 7,
 1,
 2,
 1,
 1,
 1,
 4,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 8,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 3,
 2,
 6,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 7,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 7,
 3,
 6,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 7,
 1,
 3,
 1,
 8,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 6,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 1,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 3,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [61]:
data = {'word': word_list, 'count' : word_rank}
word_data = pd.DataFrame.from_dict(data)
word_data

     word  count
0    오아시스    156
1     팬데믹      1
2      시대      1
3       내      1
4      마음      1
..    ...    ...
383    받다      1
384    미트      1
385    박스      1
386    흑자      1
387    비결      1

[388 rows x 2 columns]

In [68]:
word_data.sort_values(by=['count'], ascending=False).reset_index().drop(columns=['index'])

     word  count
0    오아시스    156
1     코멘트     32
2      상장     12
3       주     11
4       일     11
..    ...    ...
383    주다      1
384   넘기다      1
385    분과      1
386    식수      1
387    비결      1

[388 rows x 2 columns]